/**
 * BaCS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RussianDayOfWeek } from './russianDayOfWeek';

export interface CalendarSettingsDto {
  /**
   * Время начала работы локации.
   */
  availableFrom?: string;
  /**
   * Время окончания работы локации.
   */
  availableTo?: string;
  /**
   * Набор рабочих дней недели локации.
   */
  availableDaysOfWeek?: Array<RussianDayOfWeek> | null;
}
