/**
 * BaCS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface CreateReservationRequest {
  /**
   * ID ресурса для бронирования.
   */
  resourceId: string;
  /**
   * ID локации, в которой находится ресурс.
   */
  locationId: string;
  /**
   * Дата и время начала бронирования.
   */
  from: string;
  /**
   * Дата и время окончания бронирования.
   */
  to: string;
}
