/**
 * BaCS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalendarSettingsDto } from './calendarSettingsDto';

export interface CreateLocationRequest {
  /**
   * Название локации.
   */
  name: string;
  /**
   * Адресс локации.
   */
  address: string;
  /**
   * Описание локации.
   */
  description?: string | null;
  calendarSettings: CalendarSettingsDto;
}
