/**
 * BaCS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetLocationsRequest { 
    /**
     * Фильтр по ID локаций.
     */
    ids?: Array<string> | null;
    offset?: number;
    limit?: number;
}

