/**
 * BaCS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface GetReservationsReportRequest { 
    /**
     * Дата начала отчёта (включительно).
     */
    from: string;
    /**
     * Дата окончания отчёта (включительно).
     */
    to: string;
    /**
     * ID пользователя, по которому фильтровать бронирования.
     */
    userId?: string | null;
    /**
     * ID ресурса, по которому фильтровать бронирования.
     */
    resourceId?: string | null;
    /**
     * ID локации, по которой фильтровать бронирования.
     */
    locationId?: string | null;
}

