/**
 * BaCS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceType } from './resourceType';


export interface GetResourcesRequest { 
    /**
     * Фильтр по ID ресурсов.
     */
    ids?: Array<string> | null;
    /**
     * Фильтр по ID локаций.
     */
    locationIds?: Array<string> | null;
    /**
     * Фильтр по типам ресурсов.
     */
    types?: Array<ResourceType> | null;
    offset?: number;
    limit?: number;
}

