/**
 * BaCS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReservationStatus } from './reservationStatus';

export interface GetReservationsRequest {
  /**
   * Фильтр по ID резерваций.
   */
  ids?: Array<string> | null;
  /**
   * Фильтр по ID пользователей.
   */
  userIds?: Array<string> | null;
  /**
   * Фильтр по ID локаций.
   */
  locationIds?: Array<string> | null;
  /**
   * Фильтр по ID ресурсов.
   */
  resourceIds?: Array<string> | null;
  /**
   * Фильтр по статусам резерваций.
   */
  statuses?: Array<ReservationStatus> | null;
  /**
   * Фильтр по времени начала бронирования (включительно).
   */
  afterDate?: string | null;
  /**
   * Фильтр по времени окончания бронирования (включительно).
   */
  beforeDate?: string | null;
  offset?: number;
  limit?: number;
}
