/**
 * BaCS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface GetUsersRequest {
  /**
   * Фильтр по ID пользователей.
   */
  ids?: Array<string> | null;
  offset?: number;
  limit?: number;
}
