/**
 * BaCS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CalendarSettingsDto } from './calendarSettingsDto';


export interface LocationDto { 
    /**
     * ID локации.
     */
    id?: string;
    /**
     * Название локации.
     */
    name?: string | null;
    /**
     * Адрес локации.
     */
    address?: string | null;
    /**
     * Описание локации.
     */
    description?: string | null;
    /**
     * Ссылка на фотографию локации.
     */
    imageUrl?: string | null;
    calendarSettings?: CalendarSettingsDto;
    /**
     * ID администраторов локации.
     */
    adminIds?: Array<string> | null;
}

