/**
 * BaCS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LocationDto } from './locationDto';


export interface LocationDtoPaginatedResponse { 
    /**
     * Коллекция элементов.
     */
    collection?: Array<LocationDto> | null;
    /**
     * Общее количество элементов в коллекции.
     */
    totalCount?: number;
}

