/**
 * BaCS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * Машино-читаемый формат ошибок API, в соответствии со стандартом <a href=\"https://www.rfc-editor.org/rfc/rfc9457\">RFC 9457</a>.
 */
export interface ProblemDetails {
  [key: string]: any | any;

  /**
   * Тип ошибки.
   */
  type?: string | null;
  /**
   * Краткое человеко-читаемое описание ошибки.
   */
  title?: string | null;
  /**
   * HTTP-статус код ошибки.
   */
  status?: number | null;
  /**
   * Детальное человеко-читаемое описание ошибки.
   */
  detail?: string | null;
  /**
   * URI, на котором произошла ошибка.
   */
  instance?: string | null;
}
