/**
 * BaCS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ReservationStatus } from './reservationStatus';


export interface ReservationDto { 
    /**
     * ID резервации.
     */
    id?: string;
    /**
     * ID забронированного ресурса.
     */
    resourceId?: string;
    /**
     * ID локации, в которой забронирован ресурс.
     */
    locationId?: string;
    /**
     * ID пользователя, забронировавшего ресурс.
     */
    userId?: string;
    /**
     * Дата и время начала резервации.
     */
    from?: string;
    /**
     * Дата и время окончания резервации.
     */
    to?: string;
    status?: ReservationStatus;
}
export namespace ReservationDto {
}


