/**
 * BaCS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export const ReservationStatus = {
    Created: 'Created',
    Cancelled: 'Cancelled'
} as const;
export type ReservationStatus = typeof ReservationStatus[keyof typeof ReservationStatus];

