/**
 * BaCS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceType } from './resourceType';

export interface ResourceDto {
  /**
   * ID ресурса.
   */
  id?: string;
  /**
   * ID локации.
   */
  locationId?: string;
  /**
   * Название ресурса.
   */
  name?: string | null;
  /**
   * Описание ресурса.
   */
  description?: string | null;
  /**
   * Этаж, на котором расположен ресурс.
   */
  floor?: number;
  /**
   * Оборудование, прикреплённое к ресурсу.
   */
  equipment?: Array<string> | null;
  type?: ResourceType;
  /**
   * Ссылка на фотографию ресурса.
   */
  imageUrl?: string | null;
}
export namespace ResourceDto {}
