/**
 * BaCS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateReservationRequest {
  /**
   * Время начала резервации.
   */
  from: string;
  /**
   * Время окончания резервации.
   */
  to: string;
}
