/**
 * BaCS API
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ResourceType } from './resourceType';


export interface UpdateResourceRequest { 
    /**
     * Название ресурса.
     */
    name: string;
    /**
     * Описание ресурса.
     */
    description?: string | null;
    /**
     * Этаж, на котором расположен ресурс.
     */
    floor: number;
    /**
     * Оборудование, прикреплённое к ресурсу.
     */
    equipment?: Array<string> | null;
    type: ResourceType;
}
export namespace UpdateResourceRequest {
}


