/**
 * BaCS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UpdateUserRequest {
  /**
   * Email-адрес пользователя.
   */
  email?: string | null;
  /**
   * Уведомлять о бронированиях по электронной почте.
   */
  enableEmailNotifications: boolean;
}
