/**
 * BaCS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UserDto } from './userDto';

export interface UserDtoPaginatedResponse {
  /**
   * Коллекция элементов.
   */
  collection?: Array<UserDto> | null;
  /**
   * Общее количество элементов в коллекции.
   */
  totalCount?: number;
}
