/**
 * BaCS API
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export interface UserDto {
  /**
   * ID пользователя.
   */
  id?: string;
  /**
   * Email-адрес пользователя.
   */
  email?: string | null;
  /**
   * ФИО пользователя.
   */
  name?: string | null;
  /**
   * Ссылка на фотографию пользователя.
   */
  imageUrl?: string | null;
  /**
   * Уведомлять о бронированиях по электронной почте.
   */
  enableEmailNotifications?: boolean;
}
